--TODO: ตอน run snapshot แล้ว error ที่ cdb$root ซึ่งไม่ควรต้องไปเข้าถึง?
-- ทำใน CDB
ALTER SESSION SET CONTAINER = CDB$ROOT;

BEGIN
  LOOP
    -- สังเกต เราใช้ SELECT INTO เพื่อนับ session
    DECLARE
      l_cnt NUMBER;
    BEGIN
      SELECT COUNT(*)
        INTO l_cnt
        FROM v$session
       WHERE username = 'C##TESTCDC';

      -- ถ้าไม่มี session ค้างอยู่ ให้ออกจาก loop
      IF l_cnt = 0 THEN
        EXIT;
      END IF;

      -- kill ทุก session
      FOR r IN (
        SELECT sid, serial#
          FROM v$session
         WHERE username = 'C##TESTCDC'
      ) LOOP
        EXECUTE IMMEDIATE
          'ALTER SYSTEM KILL SESSION ''' || r.sid || ',' || r.serial# || ''' IMMEDIATE';
      END LOOP;
    END;
  END LOOP;

  -- ลบ user หลังจากตรวจสอบเรียบร้อย
  EXECUTE IMMEDIATE 'DROP USER C##TESTCDC CASCADE';
END;




BEGIN
  DECLARE
    cnt NUMBER;
  BEGIN
    SELECT COUNT(*) INTO cnt
    FROM DBA_USERS
    WHERE USERNAME = 'C##TESTCDC';

    IF cnt > 0 THEN
      -- ถ้ามีอยู่ ให้ลบก่อน
      EXECUTE IMMEDIATE 'DROP USER C##TESTCDC CASCADE';
    END IF;

    -- สร้าง user ใหม่ + มอบสิทธิ์ common
    EXECUTE IMMEDIATE q'[CREATE USER C##TESTCDC IDENTIFIED BY test CONTAINER=ALL]';
    EXECUTE IMMEDIATE q'[GRANT CREATE SESSION TO C##TESTCDC CONTAINER=ALL]';
    EXECUTE IMMEDIATE q'[GRANT SET CONTAINER TO C##TESTCDC CONTAINER=ALL]';
    EXECUTE IMMEDIATE q'[GRANT CONNECT, RESOURCE TO C##TESTCDC CONTAINER=ALL]';
    EXECUTE IMMEDIATE q'[GRANT SELECT ANY TABLE, SELECT_CATALOG_ROLE, EXECUTE_CATALOG_ROLE TO C##TESTCDC CONTAINER=ALL]';
  END;
END;


SELECT * FROM DBA_SYS_PRIVS WHERE PRIVILEGE = 'SET CONTAINER' AND GRANTEE = 'C##TESTCDC';



-- 🔁 1. เข้า PDB ก่อน
ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  FOR rec IN (
    SELECT owner, table_name
    FROM all_tables
    WHERE owner = 'TESTCDC'
  ) LOOP
    EXECUTE IMMEDIATE 
      'GRANT SELECT, INSERT, UPDATE, DELETE ON "' ||
      rec.owner || '"."' || rec.table_name || '" TO "C##TESTCDC"';
  END LOOP;
END;
/


    SELECT owner, table_name
    FROM all_tables
    WHERE owner = 'TESTCDC'

GRANT SELECT ON TESTCDC.TEST TO C##TESTCDC;

-- ✅ 2. สร้าง user ปกติ
--CREATE USER C##TESTCDC IDENTIFIED BY test;

-- ✅ 3. ให้สิทธิ์พื้นฐาน

GRANT UNLIMITED TABLESPACE TO C##TESTCDC;

-- ✅ 4. ให้สิทธิ์ในการสร้างและแก้ไขตาราง
GRANT CREATE TABLE TO C##TESTCDC;
GRANT ALTER ANY TABLE TO C##TESTCDC;

-- ✅ 5. ให้สิทธิ์ในการจัดการข้อมูล
GRANT INSERT ANY TABLE TO C##TESTCDC;
GRANT UPDATE ANY TABLE TO C##TESTCDC;
GRANT DELETE ANY TABLE TO C##TESTCDC;

-- ✅ 6. อนุญาตใช้งาน tablespace
ALTER USER C##TESTCDC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT SELECT ANY DICTIONARY TO C##TESTCDC;



CREATE TABLE "C##TESTCDC"."orders" (
  "id" NUMBER(10, 0) PRIMARY KEY,
  "customer_id" NUMBER(10, 0),
  "order_date" DATE,
  "__deleted" CHAR(5),
  "__op" CHAR(1),
  "__table" VARCHAR2(50),
  "__ts_ms" NUMBER(19,0)
);


ALTER TABLE C##TESTCDC."orders" MODIFY ("id" DEFAULT 0);



-- ให้สิทธิ์ที่จำเป็นกับ Debezium
GRANT CONNECT, CREATE SESSION TO C##TESTCDC;
GRANT SELECT ANY TABLE TO C##TESTCDC;
GRANT FLASHBACK ANY TABLE TO C##TESTCDC;

-- เฉพาะสำหรับ OpenLogReplicator
GRANT SELECT ON V_$DATABASE TO C##TESTCDC;
GRANT SELECT ON V_$LOG TO C##TESTCDC;
GRANT SELECT ON V_$LOGFILE TO C##TESTCDC;
GRANT SELECT ON V_$ARCHIVED_LOG TO C##TESTCDC;
GRANT SELECT ON V_$THREAD TO C##TESTCDC;
GRANT SELECT ON V_$PARAMETER TO C##TESTCDC;
GRANT SELECT ON V_$NLS_PARAMETERS TO C##TESTCDC;
GRANT SELECT ON V_$TIMEZONE_NAMES TO C##TESTCDC;


ALTER SESSION SET CONTAINER = XEPDB1;

GRANT SELECT, FLASHBACK ON XDB.XDB$TTSET TO C##TESTCDC;


GRANT SELECT, FLASHBACK ON SYS.CCOL$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.CDEF$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.COL$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.DEFERRED_STG$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.ECOL$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.LOB$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.LOBCOMPPART$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.LOBFRAG$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.OBJ$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.TAB$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.TABCOMPART$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.TABPART$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.TABSUBPART$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.TS$ TO C##TESTCDC;
GRANT SELECT, FLASHBACK ON SYS.USER$ TO C##TESTCDC;

GRANT SELECT ON SYS.V_$ARCHIVED_LOG TO C##TESTCDC;
GRANT SELECT ON SYS.V_$DATABASE TO C##TESTCDC;
GRANT SELECT ON SYS.V_$DATABASE_INCARNATION TO C##TESTCDC;
GRANT SELECT ON SYS.V_$LOG TO C##TESTCDC;
GRANT SELECT ON SYS.V_$LOGFILE TO C##TESTCDC;
GRANT SELECT ON SYS.V_$PARAMETER TO C##TESTCDC;
GRANT SELECT ON SYS.V_$STANDBY_LOG TO C##TESTCDC;
GRANT SELECT ON SYS.V_$TRANSPORTABLE_PLATFORM TO C##TESTCDC;



SELECT table_name FROM all_tables WHERE owner = 'XDB';


BEGIN
  FOR rec IN (SELECT table_name FROM all_tables WHERE owner = 'XDB') LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT, FLASHBACK ON XDB.' || rec.table_name || ' TO C##TESTCDC';
  END LOOP;
END;




