-- สร้างผู้ใช้งาน
CREATE USER C##TEST IDENTIFIED BY test;

-- ให้สิทธิ์พื้นฐาน
GRANT CONNECT, RESOURCE TO C##TEST;

-- ให้สิทธิ์เพิ่มเติมสำหรับ CDC / Debezium
GRANT SELECT ANY TABLE TO C##TEST;
GRANT FLASHBACK ANY TABLE TO C##TEST;
GRANT SELECT ANY TRANSACTION TO C##TEST;
GRANT EXECUTE_CATALOG_ROLE TO C##TEST;
GRANT UNLIMITED TABLESPACE TO C##TEST;
GRANT CREATE SESSION TO C##TEST;

-- ให้สิทธิ์อ่าน Redo Log (ใช้กับ Oracle LogMiner)
GRANT LOGMINING TO C##TEST;
