
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    mem_limit: 300m
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  mongodb_data:

