
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    mem_limit: 512m
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    mem_limit: 1g
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx768M -Xms512M"
      KAFKA_LOG_RETENTION_HOURS: 1
      KAFKA_LOG_SEGMENT_BYTES: 52428800
    networks:
      - kafka-net

  connect:
    image: debezium/connect:2.5
    restart: always
    mem_limit: 512m
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      PLUGIN_PATH: /kafka/connect
      CONNECT_PLUGIN_PATH: /kafka/connect
    volumes:
      - ./plugins:/kafka/connect
      - ./mysql-connector.json:/etc/kafka-connect/mysql-connector.json
      - ./postgres-connector.json:/etc/kafka-connect/postgres-connector.json
      - ./mssql-connector.json:/etc/kafka-connect/mssql-connector.json
      - ./kafka-connect-jdbc/kafka-connect-jdbc-10.7.4:/kafka/connect/jdbc
    networks:
      - kafka-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    mem_limit: 512m
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: debezium
      MYSQL_PASSWORD: dbz
      MYSQL_DATABASE: testdb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kafka-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    mem_limit: 1.2g
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrongPassword123
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - kafka-net
      
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kafka-net
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    mem_limit: 256m
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
  mssql_data:
  grafana_data:
  mongodb_data:
