-- Login as INVENTORY user
BEGIN
  FOR i IN 1..10 LOOP
    EXECUTE IMMEDIATE '
      CREATE TABLE inventory_' || i || ' (
        id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        field1    VARCHAR2(50),
        field2    VARCHAR2(50),
        field3    VARCHAR2(50),
        field4    VARCHAR2(50),
        field5    VARCHAR2(50),
        field6    NUMBER,
        field7    DATE,
        field8    VARCHAR2(50)
      )';
  END LOOP;
END;


DECLARE
  v_date DATE := SYSDATE;
BEGIN
  FOR i IN 1..10 LOOP
    FOR j IN 1..50 LOOP
      EXECUTE IMMEDIATE '
        INSERT INTO inventory_' || i || ' (field1, field2, field3, field4, field5, field6, field7, field8)
        VALUES (:1, :2, :3, :4, :5, :6, :7, :8)'
      USING
        'Data1_' || j,
        'Data2_' || j,
        'Data3_' || j,
        'Data4_' || j,
        'Data5_' || j,
        j,
        v_date + j,
        'Extra_' || j;
    END LOOP;
  END LOOP;
  COMMIT;
END;
/
