
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    mem_limit: 2g
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    ports:
      - "2181:2181"
    networks:
      - kafka-net


  kafka:
    image: confluentinc/cp-kafka:7.5.0
    mem_limit: 3g
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9111:9111"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx768M -Xms512M"
      #KAFKA_JMX_PORT: 9111
      #KAFKA_JMX_HOSTNAME: localhost
      #KAFKA_OPTS: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=9111:/opt/jmx-exporter/kafka.yml"
    volumes:
      - ./jmx-exporter:/opt/jmx-exporter
    networks:
      - kafka-net


  connect:
    image: quay.io/debezium/connect:3.1
    restart: always
    mem_limit: 1g
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      PLUGIN_PATH: /kafka/connect
    volumes:
      - ./plugins:/kafka/connect
      - ./wait-for-kafka.sh:/wait-for-kafka.sh
    command: ["./wait-for-kafka.sh", "/docker-entrypoint.sh", "connect-distributed", "/etc/kafka/connect-distributed.properties"]
    networks:
      - kafka-net



  oracle:
    image: oracle/database:21.3.0-xe
    container_name: oracle
    environment:
      ORACLE_PASSWORD: Oracle123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle-arch:/opt/oracle/homes/OraDBHome21cXE/dbs/arch
    networks:
      - kafka-net



  mysql:
    image: mysql:8.0
    container_name: mysql
    mem_limit: 2g
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: debezium
      MYSQL_PASSWORD: dbz
      MYSQL_DATABASE: testdb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kafka-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    mem_limit: 3g
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrongPassword123
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - kafka-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - kafka-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    mem_limit: 512m
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kafka-net

  grafana:
    image: grafana/grafana-oss:10.2.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

volumes:
  mysql_data:
  mssql_data:
  mongodb_data:
  grafana_data:
  oracle_data:

