global:
  scrape_interval: 30s

scrape_configs:
  #- job_name: 'kafka-broker'
    #static_configs:
      #- targets: ['kafka:7071']

  - job_name: 'debezium-connect'
    static_configs:
      - targets: ['connect:7073']